"""Initial migration.

Revision ID: 7f357833fd7c
Revises:
Create Date: 2024-05-10 17:35:35.512716

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7f357833fd7c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tickets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("subject", sa.String(length=256), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("email", sa.String(length=256), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "waiting_for_answer",
                "answered",
                "closed",
                name="ticketstatuses",
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tickets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tickets_email"), ["email"], unique=False)
        batch_op.create_index(batch_op.f("ix_tickets_status"), ["status"], unique=False)

    op.create_table(
        "tickets_comments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ticket_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("email", sa.String(length=256), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["ticket_id"], ["tickets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tickets_comments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tickets_comments_email"), ["email"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tickets_comments_ticket_id"), ["ticket_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tickets_comments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tickets_comments_ticket_id"))
        batch_op.drop_index(batch_op.f("ix_tickets_comments_email"))

    op.drop_table("tickets_comments")
    with op.batch_alter_table("tickets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tickets_status"))
        batch_op.drop_index(batch_op.f("ix_tickets_email"))

    op.drop_table("tickets")
    # ### end Alembic commands ###
